### PR TITLE
Fix copy paste for lists, block quotes and images

### LINKED ISSUE #107: Copy / Paste Support for Blockquotes
Implement copy / paste support for blockquotes.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fix #107 and #108

This PR implements support for NSCoding in all our custom attributes to allow them to be copy pasted, inside the editor.

It keeps the original pasteboard in place in order to allow other applications to work correctly when pasting in or copy out.

How to test:
 - Copy paste segments of text inside the editor from one place to another and check if the behaviour is correct.

Note: Lists and Blockquotes are still not updating the DOM so changes made are not reflected in the HTML view.

### CODE REVIEW

File: Aztec/Classes/Extensions/NSAttributedString+Encoding.swift [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+extension NSAttributedString
+{
+    static let pastesboardUTI = "com.wordpress.aztec.attributedString"
+
+    func archiveToData() -> Data {
+        let data = NSKeyedArchiver.archivedData(withRootObject: self)
+        return data
+    }
+
+    static func unarchive(fromData data: Data) -> NSAttributedString? {
```
Comment (jleandroperez) [inline Aztec/Classes/Extensions/NSAttributedString+Encoding.swift]: In Swift 3 style this would probably look like...

```
static func unarchive(from data: Data) -> NSAttributedString?
```

(No need to change anything though!!)

**Comment by jleandroperez** [comment]
Added two minor code comments (feel free to disregard!!). Other than that, works beautifully.

Awesome work Sergio!!!

:shipit:
