### PR TITLE
Issue/364 fix header issues when deleting

### LINKED ISSUE #364: Deleting a new line on the the end of text, with a header before crashes
How to reproduce:
 - Start the demo app
 - Write a line and set it as an header
 - Tap new line
 - Remove the new line
 - See the app crash

### PR DESCRIPTION
**Pull request by SergioEstevao**
Closes #364 

How to test:
 - Start the empty demo app
 - Tap on the Header option and select one of the size
 - Write some test
 - Tap Enter/New Line
 - Press delete.
 - Check it didn't crash.

### CODE REVIEW

File: Aztec/Classes/TextKit/TextView.swift [hunk 1]
```diff
@@ -488,7 +488,18 @@ open class TextView: UITextView {
         forceRedrawCursorAfterDelay()
     }
 
-
+    private lazy var paragraphFormatters: [AttributeFormatter] = [
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextView.swift]: I just tried changing this to `private let paragraphFormatters` and it seems to work fine.

Thoughts about switching it?

Comment (SergioEstevao) [inline Aztec/Classes/TextKit/TextView.swift]: Will do.

**Comment by diegoreymendez** [comment]
Feel free to merge when ready.  The changes are fine.
