### PR TITLE
Fix: Drag and Drop Crash

### LINKED ISSUE #727: Aztec: Crash on drag and drop in iOS 11
### Details:

Props to @frosty for spotting this one!. Parent WPiOS [Issue Here](https://github.com/wordpress-mobile/WordPress-iOS/issues/7617).

```
1. Open Aztec, and Safari side-by-side
2. Open a web page with images
3. Drag one image into Aztec
4. Tap to the right of the image, and type a new line (enter)
5. Drag another image (or the same one) in again, into the new space
6. Crash.
```

--

screen shot 2017-09-22 at 11 26 14 am

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
Upon a Drag and Drop OP (in the scenario specified below), iOS will create a new TextView stack. Since we do not have any way to setup the TextView's **attachmentDelegate**, we're converting this property into an optional one.

Fixes #727

### To test:
1. Open Aztec, and Safari side-by-side
2. Open a web page with images
3. Drag one image into Aztec
4. Tap to the right of the image, and type a new line (enter)
5. Drag another image (or the same one) in again, into the new space

Verify that Aztec does not crash.

### CODE REVIEW

File: Aztec/Classes/TextKit/TextStorage.swift [hunk 1]
```diff
@@ -103,6 +114,9 @@ open class TextStorage: NSTextStorage {
         return attachments
     }
 
+
+    // MARK: - Public Helpers
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextStorage.swift]: The word "helper" is extremely generic and not worth much for documentation.  Can you pick a more precise category name for what this section wraps (or use "Misc" if it just needs to be categorized).

In my modest opinion you can just remove this and let this method be part of the "Attachments" section.

File: Aztec/Classes/TextKit/TextStorage.swift [hunk 2]
```diff
@@ -135,7 +149,12 @@ open class TextStorage: NSTextStorage {
     /// - Returns: the preprocessed string.
     ///
     fileprivate func preprocessAttachmentsForInsertion(_ attributedString: NSAttributedString) -> NSAttributedString {
-        assert(attachmentsDelegate != nil)
+        // Ref. #727:
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextStorage.swift]: Use a link rather than issue number (since the project could very well be forked).

File: Aztec/Classes/TextKit/TextStorage.swift [hunk 3]
```diff
@@ -184,9 +203,16 @@ open class TextStorage: NSTextStorage {
         return finalString
     }
 
-    fileprivate func detectAttachmentRemoved(in range:NSRange) {
+    fileprivate func detectAttachmentRemoved(in range: NSRange) {
+        // Ref. #727:
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextStorage.swift]: Here too, URL rather than issue number.

**Review by diegoreymendez — COMMENTED** [review]
Just a few comments.  The PR works perfectly for me.

**Review by diegoreymendez — APPROVED** [review]
Nice work!

**Comment by jleandroperez** [comment]
Thanks Diego!

**Comment by XavierLost** [comment]
The attachment does not release after dragging...
