### PR TITLE
AttributeFormatter: Fixing Boundaries Check

### LINKED ISSUE #195: Blockquote: Newline causes Toggle Loop
### Steps:
1. Launch the Empty Editor Demo
2. Press the **Blockquote** Format bar button
3. Verify that the blockqute style is onscreen
4. Press **new line**
5. Verify that the blockquote is gone
6. Press **new line** again

As a result, the blockquote will be visible (again) onscreen, and you'll enter into a loop that makes it impossible to add lines below the blockquote.

### PR DESCRIPTION
**Pull request by jleandroperez**
### Details:
Issue #195 is actually a side effect of #187's patch. Apologies about that, everything was caused by a faulty boundaries check!.

### Steps:
1. Launch the Empty Editor Demo
2. Press the **Blockquote** Format bar button
3. Verify that the blockqute style is onscreen
4. Press **new line**
5. Verify that the blockquote is gone
6. Press **new line** again

Verify that the Blockquote does not show up again.

**Plus:** Run the (new) Unit Tests, and verify they pass!

Needs Review: @diegoreymendez 
Closes #195

Thanks Diego!

### CODE REVIEW

File: AztecTests/Formatters/TextListFormatterTests.swift [hunk 1]
```diff
@@ -427,6 +427,28 @@ class TextListFormatterTests: XCTestCase
         XCTAssert(list.itemNumber(in: items[0], at: 0) == 1)
         XCTAssert(list.itemNumber(in: items[0], at: 13)  == 2)
     }
+
+
+    // Verifies that the `prsent(in: at:)` helper effectively returns true, as needed.
```
Comment (diegoreymendez) [inline AztecTests/Formatters/TextListFormatterTests.swift]: `prsent` -> `present`

**Comment by jleandroperez** [comment]
Thank you Diego!!
