### PR TITLE
Fix: Blockquote Crash

### LINKED ISSUE #185: Crash when attempting to delete text.
<h3>Description & video:</h3>

Here's [a video](https://cloudup.com/cnAwcALjGNX) showing the steps to reproduce the crash.

<h3>Steps to reproduce:</h3>

1. Launch the editor, and pick the editor demo with content.
2. Select all.
3. Delete (so that the editor is empty).
4. Type a word.
5. Press backspace once.

**Expected behavior:** a single character before the caret position should be deleted from the editor.
**Actual behavior:** the editor crashes.

<h3>Stack trace:</h3>

```
2016-12-19 17:19:37.305 AztecExample[3272:170705] *** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010444dd4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000103eaf21e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001044b72b5 +[NSException raise:format:] + 197
	3   Foundation                          0x00000001039ba3b2 -[NSRLEArray objectAtIndex:effectiveRange:] + 136
	4   Aztec                               0x0000000104f625d2 _TFC5Aztec11TextStorage10attributesfT2atSi14effectiveRangeGSqGSpVSC8_NSRange___GVs10DictionarySSP__ + 82
	5   Aztec                               0x0000000104f626a2 _TToFC5Aztec11TextStorage10attributesfT2atSi14effectiveRangeGSqGSpVSC8_NSRange___GVs10DictionarySSP__ + 50
	6   Aztec                               0x0000000104f781f2 _TFE5AztecPS_18AttributeFormatter9attributefT10inTextViewCSo10UITextView2atSi_Sb + 210
	7   Aztec                               0x0000000104f8d39b _TFC5Aztec8TextViewP33_8F4EAB6D7E480E37442C64F8C132255232refreshBlockquoteAfterDeletionOffT4textCSo18NSAttributedString7atRangeVSC8_NSRange_T_ + 91
	8   Aztec                               0x0000000104f88960 _TFC5Aztec8TextView14deleteBackwardfT_T_ + 752
	9   Aztec                               0x0000000104f889f2 _TToFC5Aztec8TextView14deleteBackwardfT_T_ + 34
	10  UIKit                               0x0000000105692061 -[UIKeyboardImpl deleteBackwardAndNotify:] + 134
	11  UIKit                               0x000000010568dbc4 -[UIKeyboardImpl performKeyboardOutput:] + 551
	12  UIKit                               0x000000010568d7a3 __55-[UIKeyboardImpl handleKeyboardInput:executionContext:]_block_invoke_2 + 318
	13  UIKit                               0x0000000105f1336b -[UIKeyboardTaskQueue continueExecutionOnMainThread] + 385
	14  Foundation                          0x00000001039dde9e __NSThreadPerformPerform + 326
	15  CoreFoundation                      0x00000001043f2761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	16  CoreFoundation                      0x00000001043d798c __CFRunLoopDoSources0 + 556
	17  CoreFoundation                      0x00000001043d6e76 __CFRunLoopRun + 918
	18  CoreFoundation                      0x00000001043d6884 CFRunLoopRunSpecific + 420
	19  GraphicsServices                    0x000000010a35ca6f GSEventRunModal + 161
	20  UIKit                               0x00000001053c2c68 UIApplicationMain + 159
	21  AztecExample                        0x00000001037e52af main + 111
	22  libdyld.dylib                       0x000000010849e68d start + 1
)
```

### PR DESCRIPTION
**Pull request by jleandroperez**
### Testing

1. Launch the editor, and pick the editor demo with content.
2. Select all.
3. Delete (so that the editor is empty).
4. Type a word.
5. Press backspace once.
6. Make sure nothing crashes

@diegoreymendez i've simplified things, and will be introducing further changes in the AttributesFormatter class, so that it's decoupled from the view, in another PR.

Mind taking a look?
Fixes #185

Thanks in advance!

### CODE REVIEW

File: Aztec/Classes/TextKit/TextView.swift [hunk 1]
```diff
@@ -635,9 +634,9 @@ open class TextView: UITextView {
     ///   - text: the text being added
     ///   - range: the range of the insertion of the new text
     ///
-    private func refreshBlockquoteAfterInsertionOf(text: String, range:NSRange) {
+    private func refreshBlockquoteAfterInsertion(of text: String, at range: NSRange) {
         let formatter = BlockquoteFormatter()
-        guard formatter.attribute(inTextView: self, at: range.location) else {
+        guard formatter.present(in: textStorage, at: range.location) else {
```
Comment (diegoreymendez) [inline Aztec/Classes/TextKit/TextView.swift]: Unless I'm missing something, we could change this line to become:

```swift
guard formattingAtIndexContainsBlockquote(range.location) else {
```

Which would also allow us to remove the formatter from this method.

Comment (jleandroperez) [inline Aztec/Classes/TextKit/TextView.swift]: Nice catch!!

**Comment by jleandroperez** [comment]
@diegoreymendez all good! ready for another peek.

Thanks a lot!!
